  [[redirects]]
from = "/subwayapi/*"
to = "http://swopenAPI.seoul.go.kr/api/subway/:splat"
status = 200
force = true

[[redirects]]
from = "/busapi/*"
to = "http://ws.bus.go.kr/rest/arrive/getArrInfoByRoute?/:splat"
status = 200
force = true